# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: RCABench
    url: rcabench/
    weight: 15
  - name: Projects
    url: projects/
    weight: 25
  - name: Blog
    url: blog/
    weight: 30

# sidebar:
#   - identifier: docs
#     name: Documentation
#     pageRef: "/rcabench/"
#     weight: 1
  # - identifier: more
  #   name: Still need help?
  #   params:
  #     type: separator
  #   weight: 1
  # - identifier: community
  #   name: "Community"
  #   pageRef: "/community"
  #   weight: 2
